<option value="" selected="selected" disabled>Select Commodity</option>
<option value="Ajwan">Ajwan</option>
<option value="Alasande Gram">Alasande Gram</option>
<option value="Almond(Badam)">Almond(Badam)</option>
<option value="Alsandikai">Alsandikai</option>
<option value="Amaranthus">Amaranthus</option>
<option value="Ambada Seed">Ambada Seed</option>
<option value="Amla(Nelli Kai)">Amla(Nelli Kai)</option>
<option value="Amphophalus">Amphophalus</option>
<option value="Antawala">Antawala</option>
<option value="Anthorium">Anthorium</option>
<option value="Apple">Apple</option>
<option value="Apricot(Jardalu/Khumani)">Apricot(Jardalu/Khumani)</option>
<option value="Arecanut(Betelnut/Supari)">Arecanut(Betelnut/Supari)</option>
<option value="Arhar (Tur/Red Gram)(Whole)">Arhar (Tur/Red Gram)(Whole)</option>
<option value="Arhar Dal(Tur Dal)">Arhar Dal(Tur Dal)</option>
<option value="Ashgourd">Ashgourd</option>
<option value="Astera">Astera</option>
<option value="Avare Dal">Avare Dal</option>
<option value="Bajra(Pearl Millet/Cumbu)">Bajra(Pearl Millet/Cumbu)</option>
<option value="Balekai">Balekai</option>
<option value="Bamboo">Bamboo</option>
<option value="Banana">Banana</option>
<option value="Banana - Green">Banana - Green</option>
<option value="Barley (Jau)">Barley (Jau)</option>
<option value="Bay leaf (Tejpatta)">Bay leaf (Tejpatta)</option>
<option value="Beans">Beans</option>
<option value="Beaten Rice">Beaten Rice</option>
<option value="Beetroot">Beetroot</option>
<option value="Bengal Gram Dal (Chana Dal)">Bengal Gram Dal (Chana Dal)</option>
<option value="Bengal Gram(Gram)(Whole)">Bengal Gram(Gram)(Whole)</option>
<option value="Ber(Zizyphus/Borehannu)">Ber(Zizyphus/Borehannu)</option>
<option value="Betal Leaves">Betal Leaves</option>
<option value="Bhindi(Ladies Finger)">Bhindi(Ladies Finger)</option>
<option value="Bitter gourd">Bitter gourd</option>
<option value="Black Gram (Urd Beans)(Whole)">Black Gram (Urd Beans)(Whole)</option>
<option value="Black Gram Dal (Urd Dal)">Black Gram Dal (Urd Dal)</option>
<option value="Black pepper">Black pepper</option>
<option value="BOP">BOP</option>
<option value="Borehannu">Borehannu</option>
<option value="Bottle gourd">Bottle gourd</option>
<option value="Bran">Bran</option>
<option value="Brinjal">Brinjal</option>
<option value="Broken Rice">Broken Rice</option>
<option value="Broomstick(Flower Broom)">Broomstick(Flower Broom)</option>
<option value="Bull">Bull</option>
<option value="Bullar">Bullar</option>
<option value="Bunch Beans">Bunch Beans</option>
<option value="Butter">Butter</option>
<option value="Cabbage">Cabbage</option>
<option value="Calf">Calf</option>
<option value="Capsicum">Capsicum</option>
<option value="Cardamoms">Cardamoms</option>
<option value="Carnation">Carnation</option>
<option value="Carrot">Carrot</option>
<option value="Cashewnuts">Cashewnuts</option>
<option value="Castor Seed">Castor Seed</option>
<option value="Cauliflower">Cauliflower</option>
<option value="Chakotha">Chakotha</option>
<option value="Chapparad Avare">Chapparad Avare</option>
<option value="Chennangi Dal">Chennangi Dal</option>
<option value="Cherry">Cherry</option>
<option value="Chikoos(Sapota)">Chikoos(Sapota)</option>
<option value="Chili Red">Chili Red</option>
<option value="Chilly Capsicum">Chilly Capsicum</option>
<option value="Chow Chow">Chow Chow</option>
<option value="Chrysanthemum">Chrysanthemum</option>
<option value="Chrysanthemum(Loose)">Chrysanthemum(Loose)</option>
<option value="Cloves">Cloves</option>
<option value="Cluster beans">Cluster beans</option>
<option value="Coca">Coca</option>
<option value="Cock">Cock</option>
<option value="Cocoa">Cocoa</option>
<option value="Coconut">Coconut</option>
<option value="Coconut Oil">Coconut Oil</option>
<option value="Coconut Seed">Coconut Seed</option>
<option value="Coffee">Coffee</option>
<option value="Colacasia">Colacasia</option>
<option value="Copra">Copra</option>
<option value="Coriander(Leaves)">Coriander(Leaves)</option>
<option value="Corriander seed">Corriander seed</option>
<option value="Cotton">Cotton</option>
<option value="Cotton Seed">Cotton Seed</option>
<option value="Cow">Cow</option>
<option value="Cowpea (Lobia/Karamani)">Cowpea (Lobia/Karamani)</option>
<option value="Cowpea(Veg)">Cowpea(Veg)</option>
<option value="Cucumbar(Kheera)">Cucumbar(Kheera)</option>
<option value="Cummin Seed(Jeera)">Cummin Seed(Jeera)</option>
<option value="Custard Apple (Sharifa)">Custard Apple (Sharifa)</option>
<option value="Dalda">Dalda</option>
<option value="Delha">Delha</option>
<option value="Dhaincha">Dhaincha</option>
<option value="Drumstick">Drumstick</option>
<option value="Dry Chillies">Dry Chillies</option>
<option value="Dry Fodder">Dry Fodder</option>
<option value="Dry Grapes">Dry Grapes</option>
<option value="Duck">Duck</option>
<option value="Duster Beans">Duster Beans</option>
<option value="Egg">Egg</option>
<option value="Elephant Yam (Suran)">Elephant Yam (Suran)</option>
<option value="Field Pea">Field Pea</option>
<option value="Firewood">Firewood</option>
<option value="Fish">Fish</option>
<option value="Foxtail Millet(Navane)">Foxtail Millet(Navane)</option>
<option value="French Beans (Frasbean)">French Beans (Frasbean)</option>
<option value="Galgal(Lemon)">Galgal(Lemon)</option>
<option value="Garlic">Garlic</option>
<option value="Ghee">Ghee</option>
<option value="Gingelly Oil">Gingelly Oil</option>
<option value="Ginger(Dry)">Ginger(Dry)</option>
<option value="Ginger(Green)">Ginger(Green)</option>
<option value="Gladiolus Cut Flower">Gladiolus Cut Flower</option>
<option value="Goat">Goat</option>
<option value="Gram Raw(Chholia)">Gram Raw(Chholia)</option>
<option value="Gramflour">Gramflour</option>
<option value="Grapes">Grapes</option>
<option value="Green Avare (W)">Green Avare (W)</option>
<option value="Green Chilli">Green Chilli</option>
<option value="Green Fodder">Green Fodder</option>
<option value="Green Gram (Moong)(Whole)">Green Gram (Moong)(Whole)</option>
<option value="Green Gram Dal (Moong Dal)">Green Gram Dal (Moong Dal)</option>
<option value="Green Peas">Green Peas</option>
<option value="Ground Nut Seed">Ground Nut Seed</option>
<option value="Groundnut">Groundnut</option>
<option value="Groundnut (Split)">Groundnut (Split)</option>
<option value="Groundnut pods (raw)">Groundnut pods (raw)</option>
<option value="Guar">Guar</option>
<option value="Guar Seed(Cluster Beans Seed)">Guar Seed(Cluster Beans Seed)</option>
<option value="Guava">Guava</option>
<option value="Gur(Jaggery)">Gur(Jaggery)</option>
<option value="Gurellu">Gurellu</option>
<option value="He Buffalo">He Buffalo</option>
<option value="Hen">Hen</option>
<option value="Hippe Seed">Hippe Seed</option>
<option value="Honge seed">Honge seed</option>
<option value="Hybrid Cumbu">Hybrid Cumbu</option>
<option value="Indian Beans (Seam)">Indian Beans (Seam)</option>
<option value="Indian Colza(Sarson)">Indian Colza(Sarson)</option>
<option value="Isabgul (Psyllium)">Isabgul (Psyllium)</option>
<option value="Jack Fruit">Jack Fruit</option>
<option value="Jaffri">Jaffri</option>
<option value="Jamun(Narale Hannu)">Jamun(Narale Hannu)</option>
<option value="Jarbara">Jarbara</option>
<option value="Jasmine">Jasmine</option>
<option value="Javi">Javi</option>
<option value="Jowar(Sorghum)">Jowar(Sorghum)</option>
<option value="Jute">Jute</option>
<option value="Kabuli Chana(Chickpeas-White)">Kabuli Chana(Chickpeas-White)</option>
<option value="Karamani">Karamani</option>
<option value="Karbuja(Musk Melon)">Karbuja(Musk Melon)</option>
<option value="Kartali (Kantola)">Kartali (Kantola)</option>
<option value="Khoya">Khoya</option>
<option value="Kinnow">Kinnow</option>
<option value="Knool Khol">Knool Khol</option>
<option value="Kodo Millet(Varagu)">Kodo Millet(Varagu)</option>
<option value="Kulthi(Horse Gram)">Kulthi(Horse Gram)</option>
<option value="Lak(Teora)">Lak(Teora)</option>
<option value="Leafy Vegetable">Leafy Vegetable</option>
<option value="Lemon">Lemon</option>
<option value="Lentil (Masur)(Whole)">Lentil (Masur)(Whole)</option>
<option value="Lilly">Lilly</option>
<option value="Lime">Lime</option>
<option value="Linseed">Linseed</option>
<option value="Lint">Lint</option>
<option value="Litchi">Litchi</option>
<option value="Little gourd (Kundru)">Little gourd (Kundru)</option>
<option value="Long Melon(Kakri)">Long Melon(Kakri)</option>
<option value="Lotus">Lotus</option>
<option value="Lotus Sticks">Lotus Sticks</option>
<option value="Lukad">Lukad</option>
<option value="Mace">Mace</option>
<option value="Mahedi">Mahedi</option>
<option value="Mahua">Mahua</option>
<option value="Mahua Seed(Hippe seed)">Mahua Seed(Hippe seed)</option>
<option value="Maida Atta">Maida Atta</option>
<option value="Maize">Maize</option>
<option value="Mango">Mango</option>
<option value="Mango (Raw-Ripe)">Mango (Raw-Ripe)</option>
<option value="Marasebu">Marasebu</option>
<option value="Marget">Marget</option>
<option value="Marigold(Calcutta)">Marigold(Calcutta)</option>
<option value="Marigold(loose)">Marigold(loose)</option>
<option value="Mashrooms">Mashrooms</option>
<option value="Masur Dal">Masur Dal</option>
<option value="Mataki">Mataki</option>
<option value="Methi Seeds">Methi Seeds</option>
<option value="Methi(Leaves)">Methi(Leaves)</option>
<option value="Millets">Millets</option>
<option value="Mint(Pudina)">Mint(Pudina)</option>
<option value="Moath Dal">Moath Dal</option>
<option value="Mousambi(Sweet Lime)">Mousambi(Sweet Lime)</option>
<option value="Mustard">Mustard</option>
<option value="Mustard Oil">Mustard Oil</option>
<option value="Myrobolan(Harad)">Myrobolan(Harad)</option>
<option value="Neem Seed">Neem Seed</option>
<option value="Niger Seed (Ramtil)">Niger Seed (Ramtil)</option>
<option value="Nutmeg">Nutmeg</option>
<option value="Onion">Onion</option>
<option value="Onion Green">Onion Green</option>
<option value="Orange">Orange</option>
<option value="Orchid">Orchid</option>
<option value="Other Pulses">Other Pulses</option>
<option value="Ox">Ox</option>
<option value="Paddy(Dhan)(Basmati)">Paddy(Dhan)(Basmati)</option>
<option value="Paddy(Dhan)(Common)">Paddy(Dhan)(Common)</option>
<option value="Papaya">Papaya</option>
<option value="Papaya (Raw)">Papaya (Raw)</option>
<option value="Patti Calcutta">Patti Calcutta</option>
<option value="Peach">Peach</option>
<option value="Pear(Marasebu)">Pear(Marasebu)</option>
<option value="Peas cod">Peas cod</option>
<option value="Peas Wet">Peas Wet</option>
<option value="Peas(Dry)">Peas(Dry)</option>
<option value="Pegeon Pea (Arhar Fali)">Pegeon Pea (Arhar Fali)</option>
<option value="Pepper garbled">Pepper garbled</option>
<option value="Pepper ungarbled">Pepper ungarbled</option>
<option value="Persimon(Japani Fal)">Persimon(Japani Fal)</option>
<option value="Pigs">Pigs</option>
<option value="Pineapple">Pineapple</option>
<option value="Plum">Plum</option>
<option value="Pointed gourd (Parval)">Pointed gourd (Parval)</option>
<option value="Pomegranate">Pomegranate</option>
<option value="Potato">Potato</option>
<option value="Pumpkin">Pumpkin</option>
<option value="Raddish">Raddish</option>
<option value="Ragi (Finger Millet)">Ragi (Finger Millet)</option>
<option value="Raibel">Raibel</option>
<option value="Rajgir">Rajgir</option>
<option value="Ram">Ram</option>
<option value="Rat Tail Radish (Mogari)">Rat Tail Radish (Mogari)</option>
<option value="Resinwood">Resinwood</option>
<option value="Rice">Rice</option>
<option value="Ridge gourd(Tori)">Ridge gourd(Tori)</option>
<option value="Ridgeguard(Tori)">Ridgeguard(Tori)</option>
<option value="Rose(Local)">Rose(Local)</option>
<option value="Rose(Loose)">Rose(Loose)</option>
<option value="Round gourd">Round gourd</option>
<option value="Rubber">Rubber</option>
<option value="Sabu Dan">Sabu Dan</option>
<option value="Sabu Dana">Sabu Dana</option>
<option value="Safflower">Safflower</option>
<option value="Sajje">Sajje</option>
<option value="Same/Savi">Same/Savi</option>
<option value="Season Leaves">Season Leaves</option>
<option value="Seemebadnekai">Seemebadnekai</option>
<option value="Seetafal">Seetafal</option>
<option value="Seetapal">Seetapal</option>
<option value="Sesamum(Sesame,Gingelly,Til)">Sesamum(Sesame,Gingelly,Til)</option>
<option value="She Buffalo">She Buffalo</option>
<option value="She Goat">She Goat</option>
<option value="Sheep">Sheep</option>
<option value="Siddota">Siddota</option>
<option value="Snake gourd">Snake gourd</option>
<option value="Snakeguard">Snakeguard</option>
<option value="Soanf">Soanf</option>
<option value="Soapnut(Antawala/Retha)">Soapnut(Antawala/Retha)</option>
<option value="Soji">Soji</option>
<option value="Soyabean">Soyabean</option>
<option value="Spinach">Spinach</option>
<option value="Sponge gourd">Sponge gourd</option>
<option value="Squash(Chappal Kadoo)">Squash(Chappal Kadoo)</option>
<option value="Sugar">Sugar</option>
<option value="Sugarcane">Sugarcane</option>
<option value="Sunflower">Sunflower</option>
<option value="Sunhemp">Sunhemp</option>
<option value="Surat Beans (Papadi)">Surat Beans (Papadi)</option>
<option value="Suva (Dill Seed)">Suva (Dill Seed)</option>
<option value="Suvarna Gadde">Suvarna Gadde</option>
<option value="Sweet Potato">Sweet Potato</option>
<option value="Sweet Pumpkin">Sweet Pumpkin</option>
<option value="T.V. Cumbu">T.V. Cumbu</option>
<option value="Tamarind Fruit">Tamarind Fruit</option>
<option value="Tamarind Seed">Tamarind Seed</option>
<option value="Tapioca">Tapioca</option>
<option value="Taramira">Taramira</option>
<option value="Tender Coconut">Tender Coconut</option>
<option value="Thinai (Italian Millet)">Thinai (Italian Millet)</option>
<option value="Thogrikai">Thogrikai</option>
<option value="Thondekai">Thondekai</option>
<option value="Tinda">Tinda</option>
<option value="Tobacco">Tobacco</option>
<option value="Tomato">Tomato</option>
<option value="Toria">Toria</option>
<option value="Tube Rose(Double)">Tube Rose(Double)</option>
<option value="Tube Rose(Loose)">Tube Rose(Loose)</option>
<option value="Tube Rose(Single)">Tube Rose(Single)</option>
<option value="Turmeric">Turmeric</option>
<option value="Turmeric (raw)">Turmeric (raw)</option>
<option value="Turnip">Turnip</option>
<option value="Walnut">Walnut</option>
<option value="Water Melon">Water Melon</option>
<option value="Wheat">Wheat</option>
<option value="Wheat Atta">Wheat Atta</option>
<option value="White Peas">White Peas</option>
<option value="White Pumpkin">White Pumpkin</option>
<option value="Wood">Wood</option>
<option value="Yam">Yam</option>
<option value="Yam (Ratalu)">Yam (Ratalu)</option>
<option value="Other">Other</option>